// <auto-generated />
using ASP_NET_Razor_Page_Work_DB.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_NET_Razor_Page_Work_DB.Model
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_NET_Razor_Page_Work_DB.Model.ElectricalElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockName_f")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockX_f")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockY_f")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockZ_f")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CableDescr_f")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CableEnd_f")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CableFans_f")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CableName_f")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CableStart_f")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handl_f")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayerName_f")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Electricals");
                });
#pragma warning restore 612, 618
        }
    }
}
